import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { GeoForgeGeneratedModule, GeoforgeGeneratedSharedModule } from './generated/module.js';
import { geoforgeValidator, registerValidationChecks } from './geoforge-validator.js';
import { geoforgeValueConverter } from './geoforge-value-converter.js';
import { geoforgeScopeComputation, geoforgeScopeProvider } from './geoforge-scoping.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type geoforgeAddedServices = {
    validation: {
        geoforgeValidator: geoforgeValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type geoforgeServices = LangiumServices & geoforgeAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const geoforgeModule: Module<geoforgeServices, PartialLangiumServices & geoforgeAddedServices> = {
  parser: {
    ValueConverter: () => new geoforgeValueConverter()
  },
  validation: {
    geoforgeValidator: () => new geoforgeValidator()
  },
  references: {
    ScopeComputation: (services) => new geoforgeScopeComputation(services),
    ScopeProvider: (services) => new geoforgeScopeProvider(services),
  // Linker: (services) => new geoforgeLinker(services)
  }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function creategeoforgeServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    geoforge: geoforgeServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        GeoforgeGeneratedSharedModule
    );
    const geoforge = inject(
        createDefaultModule({ shared }),
        GeoForgeGeneratedModule,
        geoforgeModule
    );
    shared.ServiceRegistry.register(geoforge);
    registerValidationChecks(geoforge);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, geoforge };
}
